#+title: Operating Cash Flow
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup


* Introduction

The value of any financial asset is the the sum of *expected cash flows* from that asset discounted at a risk-adjusted rate.  Thus the first step in valuing any asset is determining the expected cash flows that the asset will generate.

- We pay stock and bond holders in cash, and not with measures such as 'profit'.



* Why Not Profit?

Non-cash deductions, such as Depreciation and Amortization, are made when calculating profit.

- While these deductions lower profit, they do not actually lower cash held by the firm, which can be used to pay asset holders.

Also, cash payments for certain items are not deducted when they are made, but depreciated over time.  

- This means at times profit may be higher than the available cash for investors.



* Finance Cash Flow $\neq$ Accounting Cash Flow

The term 'Cash Flow' in finance is different from the accounting 'Statement of Cash Flows'.   

Also in finance, we usually are most interested in cash flow from operating the business, and *not* cash flows from financing activities.

-  If you are going to buy a company, you are free to change how the assets are financed.  

 

* Definitions of "Cash Flow"

There are various measures of cash flow, such as Operating Cash Flow and Free Cash Flow.

- Also, there can be particular ways to calculate cash flows for unique industries (such as movie production companies).
- Some may even define "Free Cash Flow" in different ways. 

The key, however, is that we are trying to estimate the amount of cash we can regularly return to investors.

 

* A Common Definition

A very common definition is Operating Cash Flow (OCF).  

- This is cash flow from operating your firm's assets, and excludes cash flows from financing activities. 

 

* OCF

OCF is calculated as earnings before interest and taxes (EBIT) plus Depreciation (D) minus Taxes (T).

- $OCF = EBIT + D - T$

- Note, that we don't deduct interest expense even though it is a cash charge.  This is because interest expense is not an operating charge, but rather determined by how we chose to finance our assets.

 


* Interactive App

The following app will calculate OCF for any company you choose.  

- Note how different OCF can be from Net Income.


#+BEGIN_EXPORT html

  <style>
   .slidecontainer {
  width: 100%; /* Width of the outside container */
}

/* The slider itself */
.slider {
  -webkit-appearance: none;  /* Override default CSS styles */
  appearance: none;
  width: 100%; /* Full-width */
  height: 25px; /* Specified height */
  background: #d3d3d3; /* Grey background */
  outline: none; /* Remove outline */
  opacity: 0.7; /* Set transparency (for mouse-over effects on hover) */
  -webkit-transition: .2s; /* 0.2 seconds transition on hover */
  transition: opacity .2s;
}

/* Mouse-over effects */
.slider:hover {
  opacity: 1; /* Fully shown on mouse-over */
}

/* The slider handle (use -webkit- (Chrome, Opera, Safari, Edge) and -moz- (Firefox) to override default look) */
.slider::-webkit-slider-thumb {
  -webkit-appearance: none; /* Override default look */
  appearance: none;
  width: 25px; /* Set a specific slider handle width */
  height: 25px; /* Slider handle height */
  background: #4CAF50; /* Green background */
  cursor: pointer; /* Cursor on hover */
}

.slider::-moz-range-thumb {
  width: 25px; /* Set a specific slider handle width */
  height: 25px; /* Slider handle height */
  background: #4CAF50; /* Green background */
  cursor: pointer; /* Cursor on hover */
} 

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
  </style>



  <center><h2>OCF Calculator:</h2></center>
<div class="slidecontainer">
  <input type="range" min="0" max="100" value="50" class="slider" id="sales">
  <p align="center"><b>Sales: <span id="sales_out"></b></span></p>  
  <input type="range" min="0" max="100" value="50" class="slider" id="costs">
  <p align="center"><b>Costs: <span id="costs_out"></b></span></p>  
  <input type="range" min="0" max="100" value="50" class="slider" id="depreciation">
  <p align="center"><b>Depreciation: <span id="depreciation_out"></b></span></p>  
  <input type="range" min="0" max="100" value="40" class="slider" id="tax_rate">
  <p align="center"><b>Tax Rate: <span id="tax_rate_out">%</b></span></p>  
</div>

<center><button onclick="myJsFunction()">Calculate</button></center>
<center>
<br>
<table>
  <tr>
    <th>Sales</th>
    <th><span id="sales_table"></span></th>
  </tr>
  <tr>
    <th>Costs</th>
    <th><span id="costs_table"></span></th>
  </tr>
  <tr>
    <th>Depreciation</th>
    <th><span id="depreciation_table"></span></th>
  </tr>
  <tr>
    <th>EBIT</th>
    <th><span id="ebit"></span></th>
  </tr>
  <tr>
    <th>Taxes</th>
    <th><span id="taxes"></span></th>
  </tr>
  <tr>
    <th>OCF</th>
    <th><span id="ocf"></span></th>
  </tr>
</table>
</center>

    <script src="src/app1.js"></script>

#+END_EXPORT


 

* Credits and Collaboration

[[https://github.com/financial-education/operating_cash_flow][The code is here and pull requests are welcome.]]
 

